comet:
  model: Unbabel/wmt22-cometkiwi-da

huggingface:
  token: your-huggingface-token
  tokenizers_parallelism: false

engines:
  predictionguard:
    api_key: your-predictionguard-api-key
    models:
      Hermes-2-Pro-Llama-3-8B:
        languages:
          - ara
          - aym
          - cat
          - cmn
          - hrv
          - ces
          - dan
          - nld
          - eng
          - epo
          - fin
          - fra
          - glg
          - deu
          - grn
          - haw
          - heb
          - hin
          - hmn
          - hun
          - ind
          - ita
          - jpn
          - kor
          - lat
          - lav
          - ltz
          - nor
          - fas
          - pol
          - por
          - que
          - ron
          - rus
          - sco
          - srp
          - sna
          - slk
          - slv
          - spa
          - swe
          - tha
          - tur
          - ukr
          - vie
      Hermes-2-Pro-Mistral-7B:
        languages:
          - ara
          - aym
          - cat
          - cmn
          - hrv
          - ces
          - dan
          - nld
          - eng
          - epo
          - fin
          - fra
          - glg
          - deu
          - grn
          - haw
          - heb
          - hin
          - hmn
          - hun
          - ind
          - ita
          - jpn
          - kor
          - lat
          - lav
          - ltz
          - nor
          - fas
          - pol
          - por
          - que
          - ron
          - rus
          - sco
          - srp
          - sna
          - slk
          - slv
          - spa
          - swe
          - tha
          - tur
          - ukr
          - vie
      Neural-Chat-7B:
        languages:
          - eng
          - cmn
  deepl:
    api_key: your-deepl-api-key
    languages:
      - ara
      - bul
      - cmn
      - ces
      - dan
      - nld
      - eng
      - est
      - fin
      - fra
      - deu
      - hun
      - ind
      - ita
      - jpn
      - kor
      - lav
      - lit
      - ell
      - nor
      - pol
      - por
      - ron
      - rus
      - slk
      - slv
      - spa
      - swe
      - tur
      - ukr
  openai:
    api_key: your-openai-api-key
    model: gpt-3.5-turbo
    languages:
      - afr
      - sqi
      - ara
      - hye
      - asm
      - aze
      - eus
      - bel
      - ben
      - bos
      - bul
      - mya
      - cat
      - cmn
      - hrv
      - ces
      - dan
      - nld
      - eng
      - est
      - fil
      - fin
      - fra
      - glg
      - kat
      - deu
      - guj
      - hat
      - hau
      - heb
      - hin
      - hmn
      - hun
      - isl
      - ibo
      - ind
      - gle
      - ita
      - jpn
      - jav
      - kan
      - kaz
      - khm
      - kin
      - kor
      - kur
      - lao
      - lav
      - lit
      - ltz
      - mkd
      - mlg
      - zlm
      - mal
      - mlt
      - mri
      - mar
      - ell
      - mon
      - npi
      - nor
      - ory
      - orm
      - fas
      - pol
      - por
      - ron
      - rus
      - smo
      - gla
      - srp
      - sna
      - snd
      - sin
      - slk
      - slv
      - som
      - spa
      - sun
      - swh
      - swe
      - tgl
      - tgk
      - tam
      - tat
      - tel
      - tha
      - tir
      - tur
      - tuk
      - ukr
      - urd
      - vie
      - cym
      - wol
      - xho
      - yid
      - yor
      - zul
  custom:
    models:
      model_name:
        url: https://your-custom-url
        api_key: your-custom-api-key
        languages:
          - eng
          - fra
          - deu
          - cmn
